# Generated by Django 4.1.5 on 2023-01-23 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255, unique=True)),
                ('recipe_category', models.CharField(choices=[('veg', 'VEG'), ('non veg', 'NON-VEG')], max_length=255)),
                ('dish_img', models.FileField(max_length=555, upload_to='dish-img/')),
                ('recipe_desc', models.TextField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
